version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      SECRET_KEY: q#br=ggq_)j+c@2zrvr0hpxl+0di(@!l!#3u7gem-dgs0nw#l4
      DEBUG: 1
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis

  worker:
    build: .
    command: python manage.py rqworker default
    environment:
      SECRET_KEY: q#br=ggq_)j+c@2zrvr0hpxl+0di(@!l!#3u7gem-dgs0nw#l4
      DEBUG: 1
    volumes:
      - .:/app
    depends_on:
      - web

  redis:
    image: redis:latest

  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: db_django
    volumes:
      - db_data:/var/lib/postgresql/data/
    ports:
      - '5432'

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: 1234
    volumes:
       - pgadmin_data:/var/lib/pgadmin/data
    ports:
      - '5050:80'

volumes:
  db_data:
  pgadmin_data:
